<a href="https://colab.research.google.com/github/takashi4488/rabbit_challenge/blob/main/1_1_forward_propagation_after.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 準備

## Google Colab 用の処理

下記を実行します
- ドライブのマウント
- ノートブックファイルと同じフォルダへの移動

Googleドライブのマイドライブ を基準に DNN_code/DNN_code_colab_day1 フォルダを置くことを仮定しています。必要に応じて，パスを変更してください．

In [2]:
# Google Colab での実行かを調べる
import sys
import os
ENV_COLAB = True  if 'google.colab' in sys.modules else False

# google drive のマウント
if ENV_COLAB:
  from google.colab import drive
  drive.mount('/content/drive')
  os.chdir('/content/drive/MyDrive/ML-E検定/DNN_code_colab_day1/notebook')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## sys.pathの設定

In [3]:
import sys
sys.path.append(os.pardir)  # 親ディレクトリのファイルをインポートするための設定

# importと関数定義

In [4]:
import numpy as np
from common import functions

def print_vec(text, vec):
    print("*** " + text + " ***")
    print(vec)
    print("shape: " + str(vec.shape))
    print("")


# 順伝播（単層・単ユニット）

In [5]:
# 順伝播（単層・単ユニット）

# 重み
W = np.array([[0.1], [0.2]])

## 試してみよう_配列の初期化
#W = np.zeros(2)
#W = np.ones(2)
#W = np.random.rand(2)
#W = np.random.randint(5, size=(2))

print_vec("重み", W)


# バイアス
b = np.array(0.5)

## 試してみよう_数値の初期化
#b = np.random.rand() # 0~1のランダム数値
#b = np.random.rand() * 10 -5  # -5~5のランダム数値

print_vec("バイアス", b)

# 入力値
x = np.array([2, 3])
print_vec("入力", x)


# 総入力
u = np.dot(x, W) + b
print_vec("総入力", u)

# 中間層出力
z = functions.relu(u)
print_vec("中間層出力", z)


*** 重み ***
[[0.1]
 [0.2]]
shape: (2, 1)

*** バイアス ***
0.5
shape: ()

*** 入力 ***
[2 3]
shape: (2,)

*** 総入力 ***
[1.3]
shape: (1,)

*** 中間層出力 ***
[1.3]
shape: (1,)



# 順伝播（単層・複数ユニット）

In [6]:
# 順伝播（単層・複数ユニット）

# 重み
W = np.array([
    [0.1, 0.2, 0.3,0],
    [0.2, 0.3, 0.4, 0.5],
    [0.3, 0.4, 0.5, 1],
])

## 試してみよう_配列の初期化
#W = np.zeros((4,3))
#W = np.ones((4,3))
#W = np.random.rand(4,3)
#W = np.random.randint(5, size=(4,3))

print_vec("重み", W)

# バイアス
b = np.array([0.1, 0.2, 0.3])
print_vec("バイアス", b)

# 入力値
x = np.array([1.0, 5.0, 2.0, -1.0])
print_vec("入力", x)

#  総入力
u = np.dot(W, x) + b
print_vec("総入力", u)

# 中間層出力
z = functions.sigmoid(u)
print_vec("中間層出力", z)


*** 重み ***
[[0.1 0.2 0.3 0. ]
 [0.2 0.3 0.4 0.5]
 [0.3 0.4 0.5 1. ]]
shape: (3, 4)

*** バイアス ***
[0.1 0.2 0.3]
shape: (3,)

*** 入力 ***
[ 1.  5.  2. -1.]
shape: (4,)

*** 総入力 ***
[1.8 2.2 2.6]
shape: (3,)

*** 中間層出力 ***
[0.85814894 0.90024951 0.93086158]
shape: (3,)



# 順伝播（3層・複数ユニット）

In [7]:
# 順伝播（3層・複数ユニット）

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")
    network = {}

    input_layer_size = 3
    hidden_layer_size_1=10
    hidden_layer_size_2=5
    output_layer_size = 4

    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    network['W1'] = np.random.rand(input_layer_size, hidden_layer_size_1)
    network['W2'] = np.random.rand(hidden_layer_size_1,hidden_layer_size_2)
    network['W3'] = np.random.rand(hidden_layer_size_2,output_layer_size)

    network['b1'] =  np.random.rand(hidden_layer_size_1)
    network['b2'] =  np.random.rand(hidden_layer_size_2)
    network['b3'] =  np.random.rand(output_layer_size)

    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("重み3", network['W3'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )
    print_vec("バイアス3", network['b3'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):

    print("##### 順伝播開始 #####")

    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    # 1層の総入力
    u1 = np.dot(x, W1) + b1

    # 1層の総出力
    z1 = functions.relu(u1)

    # 2層の総入力
    u2 = np.dot(z1, W2) + b2

    # 2層の総出力
    z2 = functions.relu(u2)

    # 出力層の総入力
    u3 = np.dot(z2, W3) + b3

    # 出力層の総出力
    y = u3

    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("中間層出力2", z2)
    print_vec("総入力2", u2)
    print_vec("出力", y)
    print("出力合計: " + str(np.sum(y)))

    return y, z1, z2

# 入力値
x = np.array([1., 2., 4.])
print_vec("入力", x)

# ネットワークの初期化
network =  init_network()

y, z1, z2 = forward(network, x)

*** 入力 ***
[1. 2. 4.]
shape: (3,)

##### ネットワークの初期化 #####
*** 重み1 ***
[[0.50900615 0.53803497 0.13376786 0.53019436 0.82298266 0.41523053
  0.44911318 0.47417342 0.69728813 0.96285728]
 [0.38411245 0.05190158 0.59635176 0.10649516 0.85842426 0.84719628
  0.06507944 0.12676259 0.54090435 0.38336957]
 [0.07105075 0.6434098  0.3621439  0.31155137 0.65196628 0.14630712
  0.95067656 0.66267266 0.29655807 0.37776352]]
shape: (3, 10)

*** 重み2 ***
[[0.6824253  0.53761347 0.19724021 0.79321257 0.78968424]
 [0.29432221 0.98948832 0.84697478 0.01644626 0.35408385]
 [0.84416526 0.894241   0.42918694 0.17019709 0.87105336]
 [0.14720459 0.32738327 0.40306833 0.63163827 0.27727492]
 [0.02622367 0.8769113  0.85379304 0.49659959 0.71653437]
 [0.75690906 0.2282286  0.28964316 0.30390671 0.19891545]
 [0.15869957 0.34530407 0.86072858 0.06112814 0.22787794]
 [0.0474865  0.17367388 0.140826   0.03775876 0.25008778]
 [0.76774794 0.91927576 0.73435793 0.15396923 0.70555978]
 [0.75865975 0.769079   0.75262714

In [8]:
np.random.rand(3, 3)

array([[0.74066348, 0.10160935, 0.34239727],
       [0.30955845, 0.16180958, 0.74698594],
       [0.96248169, 0.18680226, 0.69867827]])

# 多クラス分類（2-3-4ネットワーク）

In [9]:
# 多クラス分類
# 2-3-4ネットワーク

# ！試してみよう_ノードの構成を 3-5-6 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成

    network = {}

    input_layer_size = 3
    hidden_layer_size=50
    output_layer_size = 6

    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    network['W1'] = np.random.rand(input_layer_size, hidden_layer_size)
    network['W2'] = np.random.rand(hidden_layer_size,output_layer_size)

    network['b1'] =  np.random.rand(hidden_layer_size)
    network['b2'] =  np.random.rand(output_layer_size)

    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):

    print("##### 順伝播開始 #####")
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']

    # 1層の総入力
    u1 = np.dot(x, W1) + b1

    # 1層の総出力
    z1 = functions.relu(u1)

    # 2層の総入力
    u2 = np.dot(z1, W2) + b2

    # 出力値
    y = functions.softmax(u2)

    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))

    return y, z1

## 事前データ
# 入力値
x = np.array([1., 2.,  3.])

# 目標出力
d = np.array([0, 0, 0, 1, 0, 0])

# ネットワークの初期化
network =  init_network()

# 出力
y, z1 = forward(network, x)

# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("交差エントロピー誤差",  loss)



##### ネットワークの初期化 #####
*** 重み1 ***
[[6.44413854e-01 6.62066920e-01 3.09934773e-01 1.99610612e-01
  1.60328564e-01 8.48334340e-01 7.02099686e-01 1.54319713e-01
  4.50165072e-01 2.07908396e-01 5.98177736e-01 7.96537796e-01
  9.07042493e-02 9.06764928e-01 9.98937195e-01 7.31008272e-01
  8.88265758e-01 6.15915233e-01 6.85428481e-01 5.85780779e-02
  1.56385166e-01 7.88935152e-01 9.66628102e-01 8.11009783e-01
  4.99760576e-01 9.82211448e-01 5.84098109e-01 4.47375842e-02
  8.76803321e-01 9.21249077e-01 4.15060043e-01 1.35559225e-01
  7.60408477e-01 7.93470490e-01 4.59031210e-03 1.73008741e-01
  8.21824064e-01 5.18559203e-01 8.33425457e-01 2.90734745e-01
  1.96750504e-02 8.87293688e-01 9.70631321e-01 9.63428356e-01
  7.80261720e-01 5.33532501e-01 4.94785589e-02 4.76766514e-01
  2.60492612e-02 8.36500028e-01]
 [9.59259176e-01 4.22578931e-01 5.44354336e-02 4.36493019e-01
  6.38024299e-01 4.17531468e-01 6.56729407e-01 4.22445615e-01
  8.86407249e-01 5.60564212e-01 7.51568718e-01 7.87190470e-05
  

# 回帰（2-3-2ネットワーク）

In [10]:
# 回帰
# 2-3-2ネットワーク

# ！試してみよう_ノードの構成を 3-5-4 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    input_layer_size = 3
    hidden_layer_size=50
    output_layer_size = 2

    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    network['W1'] = np.random.rand(input_layer_size, hidden_layer_size)
    network['W2'] = np.random.rand(hidden_layer_size,output_layer_size)

    network['b1'] =  np.random.rand(hidden_layer_size)
    network['b2'] =  np.random.rand(output_layer_size)

    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")

    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層の総出力
    z1 = functions.relu(u1)
    # 出力層の総入力
    u2 = np.dot(z1, W2) + b2
    # 出力層の総出力
    y = u2

    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))

    return y, z1

# 入力値
x = np.array([1., 2., 3.])
network =  init_network()
y, z1 = forward(network, x)
# 目標出力
d = np.array([2., 4.])
# 誤差
loss = functions.mean_squared_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("二乗誤差",  loss)


##### ネットワークの初期化 #####
*** 重み1 ***
[[1.38985538e-01 7.04327476e-01 7.85209912e-01 4.33813989e-02
  3.78737301e-01 3.63014831e-01 3.35880918e-01 5.50535107e-01
  7.68014217e-01 9.84147871e-04 9.92880196e-01 7.72888139e-01
  7.46972168e-01 7.13494473e-01 5.04350078e-01 2.57407403e-01
  7.71137444e-01 2.36611913e-01 7.78267871e-01 9.57112344e-02
  3.77511153e-01 2.38041596e-01 2.84574515e-01 7.34675160e-01
  4.06372824e-01 8.59475744e-01 1.60269001e-01 5.93554704e-01
  1.63218033e-01 5.06326985e-02 6.41404202e-01 2.63412695e-01
  9.66849790e-01 7.54495167e-03 7.60929011e-01 4.30049300e-01
  2.48818254e-01 6.12514576e-01 9.26687912e-01 7.22905020e-01
  2.25268776e-01 7.16201048e-01 3.52008420e-01 4.44789080e-01
  8.50404580e-01 4.02055463e-02 3.85608868e-01 5.33442055e-01
  3.21101448e-01 2.18569350e-01]
 [5.85142271e-01 9.19223926e-01 6.34539265e-01 4.35363431e-01
  1.33625701e-01 6.43374320e-02 8.01757990e-01 2.82386554e-01
  4.53822356e-01 8.40033025e-01 2.38286870e-02 2.58326209e-01
  

# 2値分類（2-3-1ネットワーク）

In [11]:
# 2値分類
# 2-3-1ネットワーク

# ！試してみよう_ノードの構成を 5-10-20-1 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    network = {}
    network['W1'] = np.array([
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5,0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1]
    ])
    network['W2'] = np.random.rand(10, 20)
    network['W3'] = np.random.rand(20, 1)

    network['b1'] = np.random.rand(10)
    network['b2'] =np.random.rand(20)
    network['b3'] =np.random.rand(1)

    return network


# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")

    W1, W2, W3 = network['W1'], network['W2'],network['W3']
    b1, b2, b3 = network['b1'], network['b2'],network['b3']

    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層1の総出力
    z1 = functions.relu(u1)
    # 隠れ層２層への総入力
    u2 = np.dot(z1, W2) + b2
    # 隠れ層2の出力
    z2 = functions.relu(u2)

    u3 = np.dot(z2, W3) + b3
    z3 = functions.sigmoid(u3)
    y = z3
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))

    return y, z1

# 入力値
x = np.array([1., 2.,2.,4.,5.])

# 目標出力
d = np.array([1])
network =  init_network()
y, z1 = forward(network, x)
# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("交差エントロピー誤差",  loss)

##### ネットワークの初期化 #####
##### 順伝播開始 #####
*** 総入力1 ***
[2.13290316 5.09288125 7.7647057  1.96308277 4.23599794 7.40367607
 2.28989146 4.40956368 7.44212503 2.18019515]
shape: (10,)

*** 中間層出力1 ***
[2.13290316 5.09288125 7.7647057  1.96308277 4.23599794 7.40367607
 2.28989146 4.40956368 7.44212503 2.18019515]
shape: (10,)

*** 総入力2 ***
[27.62049942 20.16486202 29.05137149 26.77193078 31.94834001 22.18986189
 22.41249552 22.21436162 16.54755488 24.31296712 25.94195771 22.57446155
 19.48703531 24.21618755 15.72081419 23.54272652 22.3190561  20.0778161
 17.77985194 32.54044218]
shape: (20,)

*** 出力1 ***
[1.]
shape: (1,)

出力合計: 1.0

##### 結果表示 #####
*** 中間層出力 ***
[2.13290316 5.09288125 7.7647057  1.96308277 4.23599794 7.40367607
 2.28989146 4.40956368 7.44212503 2.18019515]
shape: (10,)

*** 出力 ***
[1.]
shape: (1,)

*** 訓練データ ***
[1]
shape: (1,)

*** 交差エントロピー誤差 ***
-9.999999505838704e-08
shape: ()

